In [1]:
!pip3 install decorator==5.0.9

# !pip3 install --user decorator==4.3.0 # (ignore waring for availability of newer version)
# !pip3 install --user networkx==2.3


import numpy as np
import pandas as pd
import networkx as nx
import seaborn as sns

import os

from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as patches

seed = 0
np.random.seed(seed)

Defaulting to user installation because normal site-packages is not writeable


In [2]:
#Path to the target csv file. This notebook should be in the same folder as the csv-data file

path = os.getcwd()
print(path)


/Users/fmd/Desktop/USI/Semester_4/Data_Analytics/Autonomous-Systems


In [3]:
#convert the data to a pandas dataframe. 
data = pd.read_csv(path+'/11_Autonomous_Systems.csv',index_col=0)
print(data)

                Zeus  Hera  Poseidon  Demeter  Athena  Apollo  Artemis  Ares  \
ComputerNumber                                                                 
1                  0     0         0        0       1       0        0     0   
2                  0     0         0        0       1       0        0     0   
3                  0     0         0        1       0       0        0     0   
4                  0     0         0        1       0       0        0     0   
5                  0     0         0        0       1       0        0     0   
...              ...   ...       ...      ...     ...     ...      ...   ...   
149                0     0         0        0       1       0        0     1   
150                0     0         0        0       0       0        0     0   
151                0     0         0        0       1       0        0     1   
152                0     0         0        0       1       0        0     1   
153                1     0         0    

In [4]:
#Check that there aren't any missing values in the dataset
check=data.isnull().any().sum()
if check == 0:
    print('There are no missing values in the dataset')
else:
    print('There are missing values in the dataset')


There are no missing values in the dataset


In [5]:
#Check that all values are binary
check = data.columns[data.isin([0,1]).all()]
if len(check) == data.shape[1]:
    print('All values in the columns are binary')

All values in the columns are binary


In [6]:
#After printing the data we can notice there are 153 rows and 21 columns. The index represent
#the computers labeled as numbers and the columns are titled after greek goods and have binary values.

#We can infer that the 21 columns represent the servers that computers can connect to. The value one (1)
#represents a connection and conversely, the value zero (0) shows no connection with the server. 

#From here we can 
#also infer that a computer can only be connected with a server and a server can only be connected with a computer. 


In [7]:
#construncting the dataframe
col_name=[]
for column_headers in data.columns:
    col_name.append(column_headers)

weighted_adj=[]
for i in col_name:
    row=[]
    for j in col_name:
        
        a=data.loc[:,i][data[i]==1]
        b=data.loc[:,j][data[j]==1]
        array1 = a.index.to_numpy()
        array2 = b.index.to_numpy()
        inter= list(set(array1) & set(array2))
        if i!= j:
            row.append(len(inter))
        else:
            row.append(0)
        
    weighted_adj.append(row)

# print(weighted_adj)
adj=np.array(weighted_adj)
print(adj.shape)
print(adj)
ind = np.unravel_index(np.argmax(adj, axis=None), adj.shape)

print(adj[ind])
adj=adj/(adj[ind])

    

(21, 21)
[[ 0  0  1  0  4  4  2  4 12  2  0  2  3 11  1  4  3  9  4  4  5]
 [ 0  0  0  0  6  0  0  5  0  0  0  0  0  3  1  0  0  0  0  0  0]
 [ 1  0  0  0  1  6  0  3  1  0  0  0  0  8  0  2  0  0  2  1  0]
 [ 0  0  0  0  1  0  0  1  0  2  7  0  1  9  0  0  1  0  0  1  2]
 [ 4  6  1  1  0  5  2 33  0  6  1  5  5 21  6  1  4  0  1  4  3]
 [ 4  0  6  0  5  0  2  5  2  2  0  0  0 14  0  2  1  1  2  3  3]
 [ 2  0  0  0  2  2  0  2  2  0  0  0  0  2  0  1  2  2  1  1  2]
 [ 4  5  3  1 33  5  2  0  1  4  1  1  4 19  2  3  4  1  3  4  4]
 [12  0  1  0  0  2  2  1  0  1  0  2  2  6  1  0  2 11  0  5  2]
 [ 2  0  0  2  6  2  0  4  1  0  3  0  0 14  1  0  1  0  0  4  4]
 [ 0  0  0  7  1  0  0  1  0  3  0  0  0  7  0  0  1  0  0  1  2]
 [ 2  0  0  0  5  0  0  1  2  0  0  0  4  0  4  0  0  2  0  0  0]
 [ 3  0  0  1  5  0  0  4  2  0  0  4  0  0  4  0  0  3  0  0  0]
 [11  3  8  9 21 14  2 19  6 14  7  0  0  0  0  5  9  3  5  7 14]
 [ 1  1  0  0  6  0  0  2  1  1  0  4  4  0  0  0  0  2  0  0  0]
 

In [8]:
G = nx.from_numpy_matrix(adj, create_using=nx.DiGraph)
layout = nx.spring_layout(G)
nx.draw(G, layout)
 
nx.draw_networkx_edge_labels(G, pos=layout)
plt.show()

NetworkXError: random_state_index is incorrect

In [ ]:
data.describe()

In [ ]:
heapMapCorrFeature = data.corr()
#print(heapMapCorrFeature)
print(type(heapMapCorrFeature))


aa=heapMapCorrFeature.values.tolist()

print(argmin(heapMapCorrFeature))


In [ ]:
a=data.loc[:,'Hestia'][data['Hestia']==1]

print(a)
print(len(a))

array1 = a.index.to_numpy()
print(array1)


In [ ]:
a=data.loc[:,'Granite'][data['Granite']==1]

print(a)
print(len(a))

b=a.to_frame(name='ComputerNumber')
array2 = a.index.to_numpy()
print(array2)


In [ ]:
array1=set()
